name: Flux diff
description: "Github Action that presents a summary of the difference between your changes and the current state in the cluster"
branding:
  icon: align-justify
  color: blue
inputs:
  cluster-kustomization-path:
    description: "Path to the flux kustomization files."
    required: true
    default: "clusters/dev/"
  kustomization-directories:
    description: "List of directories containing kustomization files that are deployed by flux."
    required: true
    default: "__ALL__"
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: fluxdiff.sh ${{ inputs.cluster-kustomization-path }} "${{ inputs.kustomization-directories }}" >> $GITHUB_STEP_SUMMARY
      shell: bash
